/* Emoji dataset — curated 300 common emojis with search keywords */
window.EMOJI_DATA = {
  categories: [
    { id: 'recent',   label: '🕒 Recent',    emojis: [] },
    { id: 'smileys',  label: '😀 Smileys',   emojis: [
      {e:'😀',k:'grinning smile happy'},{e:'😃',k:'smile happy big eyes'},{e:'😄',k:'happy smile'},{e:'😁',k:'beaming smile'},
      {e:'😆',k:'laugh squinting'},{e:'😅',k:'sweat smile'},{e:'🤣',k:'rofl laugh'},{e:'😂',k:'joy laugh cry'},
      {e:'🙂',k:'smile slight'},{e:'🙃',k:'upside down'},{e:'😉',k:'wink'},{e:'😊',k:'blush happy'},
      {e:'😇',k:'innocent angel'},{e:'🥰',k:'love smile hearts'},{e:'😍',k:'heart eyes love'},{e:'🤩',k:'star struck'},
      {e:'😘',k:'kiss'},{e:'😗',k:'kiss'},{e:'😚',k:'kiss closed'},{e:'😋',k:'yum tasty'},
      {e:'😛',k:'tongue'},{e:'😜',k:'wink tongue'},{e:'🤪',k:'zany crazy'},{e:'😎',k:'cool sunglasses'},
      {e:'🤓',k:'nerd'},{e:'🧐',k:'monocle curious'},{e:'😏',k:'smirk'},{e:'😒',k:'unamused'},
      {e:'😞',k:'sad disappointed'},{e:'😔',k:'pensive sad'},{e:'😟',k:'worried'},{e:'😕',k:'confused'},
      {e:'🙁',k:'frown'},{e:'☹️',k:'frown'},{e:'😣',k:'persevere'},{e:'😖',k:'confounded'},
      {e:'😫',k:'tired'},{e:'😩',k:'weary'},{e:'🥺',k:'pleading'},{e:'😢',k:'cry sad'},
      {e:'😭',k:'sob cry'},{e:'😤',k:'triumph steam'},{e:'😠',k:'angry'},{e:'😡',k:'rage pouting'},
      {e:'🤬',k:'cursing angry'},{e:'🤯',k:'mind blown exploding head'},{e:'😳',k:'flushed'},{e:'🥵',k:'hot'},
      {e:'🥶',k:'cold'},{e:'😱',k:'scream shock'},{e:'😨',k:'fear'},{e:'😰',k:'anxious sweat'},
      {e:'🤔',k:'think thinking'},{e:'🤨',k:'eyebrow raised suspicious'},{e:'😐',k:'neutral'},{e:'😑',k:'expressionless'},
      {e:'😶',k:'no mouth'},{e:'🫠',k:'melting'},{e:'😴',k:'sleep sleeping'},{e:'😪',k:'sleepy tired'},
      {e:'🤤',k:'drool'},{e:'🤧',k:'sneeze sick'},{e:'🤒',k:'sick fever'},{e:'🤕',k:'head bandage'},
      {e:'🥳',k:'party celebrate'},{e:'🥸',k:'disguise'},{e:'😷',k:'mask sick'},{e:'🤠',k:'cowboy'}
    ]},
    { id: 'people', label: '👥 People', emojis: [
      {e:'👋',k:'wave hello hi'},{e:'🤚',k:'raised hand'},{e:'🖐️',k:'hand'},{e:'✋',k:'stop hand'},
      {e:'🖖',k:'spock vulcan'},{e:'👌',k:'ok'},{e:'🤌',k:'pinched'},{e:'🤏',k:'pinch small'},
      {e:'✌️',k:'peace victory'},{e:'🤞',k:'crossed fingers luck'},{e:'🤟',k:'love you'},{e:'🤘',k:'rock horns'},
      {e:'🤙',k:'call me shaka'},{e:'👈',k:'point left'},{e:'👉',k:'point right'},{e:'👆',k:'point up'},
      {e:'🖕',k:'middle finger'},{e:'👇',k:'point down'},{e:'☝️',k:'index up'},{e:'👍',k:'thumbs up like'},
      {e:'👎',k:'thumbs down dislike'},{e:'✊',k:'fist'},{e:'👊',k:'fist bump punch'},{e:'🤛',k:'left fist'},
      {e:'🤜',k:'right fist'},{e:'👏',k:'clap applause'},{e:'🙌',k:'raised hands celebrate'},{e:'👐',k:'open hands'},
      {e:'🤲',k:'palms up'},{e:'🤝',k:'handshake deal'},{e:'🙏',k:'pray thanks please'},{e:'💪',k:'muscle strong flex'},
      {e:'🦾',k:'mechanical arm'},{e:'🧠',k:'brain'},{e:'👀',k:'eyes look'},{e:'👁️',k:'eye'},
      {e:'👶',k:'baby'},{e:'🧒',k:'child'},{e:'👦',k:'boy'},{e:'👧',k:'girl'},
      {e:'🧑',k:'person'},{e:'👨',k:'man'},{e:'👩',k:'woman'},{e:'🧓',k:'older person'},
      {e:'🧑‍💻',k:'coder developer'},{e:'👨‍💻',k:'man coder'},{e:'👩‍💻',k:'woman coder'},{e:'🧑‍🎨',k:'artist'},
      {e:'🧑‍🚀',k:'astronaut space'},{e:'🧑‍🎓',k:'student graduate'},{e:'🥷',k:'ninja'},{e:'🧙',k:'wizard magic'},
      {e:'🧚',k:'fairy'},{e:'🧛',k:'vampire'},{e:'🧟',k:'zombie'},{e:'👑',k:'crown'}
    ]},
    { id: 'objects', label: '💡 Objects', emojis: [
      {e:'💻',k:'laptop computer'},{e:'🖥️',k:'desktop computer'},{e:'⌨️',k:'keyboard'},{e:'🖱️',k:'mouse'},
      {e:'🖨️',k:'printer'},{e:'📱',k:'phone mobile'},{e:'☎️',k:'phone telephone'},{e:'📞',k:'phone'},
      {e:'📟',k:'pager'},{e:'📠',k:'fax'},{e:'📡',k:'satellite'},{e:'🔋',k:'battery'},
      {e:'🔌',k:'plug electric'},{e:'💡',k:'lightbulb idea'},{e:'🔦',k:'flashlight'},{e:'🕯️',k:'candle'},
      {e:'📷',k:'camera photo'},{e:'📸',k:'camera flash'},{e:'📹',k:'video camera'},{e:'🎥',k:'movie camera film'},
      {e:'🎞️',k:'film strip'},{e:'📽️',k:'film projector'},{e:'📺',k:'tv television'},{e:'📻',k:'radio'},
      {e:'🎙️',k:'mic studio'},{e:'🎚️',k:'slider level'},{e:'🎛️',k:'knobs control'},{e:'⏰',k:'alarm clock'},
      {e:'⏱️',k:'stopwatch'},{e:'⏲️',k:'timer'},{e:'🕰️',k:'mantelpiece clock'},{e:'⌛',k:'hourglass'},
      {e:'⏳',k:'hourglass flowing'},{e:'🎮',k:'video game'},{e:'🕹️',k:'joystick'},{e:'🎰',k:'slot machine'},
      {e:'🧩',k:'puzzle piece'},{e:'🎲',k:'dice'},{e:'♟️',k:'chess pawn'},{e:'🎭',k:'theater masks'},
      {e:'🎨',k:'art palette'},{e:'🧵',k:'thread'},{e:'🧶',k:'yarn'},{e:'👓',k:'glasses'},
      {e:'🕶️',k:'sunglasses'},{e:'🔬',k:'microscope science research'},{e:'🔭',k:'telescope space'},{e:'📡',k:'dish'},
      {e:'💉',k:'syringe medical'},{e:'💊',k:'pill medicine'},{e:'🩺',k:'stethoscope'},{e:'🧬',k:'dna'},
      {e:'🧫',k:'petri dish'},{e:'🧪',k:'test tube'},{e:'🔮',k:'crystal ball'},{e:'🧿',k:'evil eye'},
      {e:'📚',k:'books library'},{e:'📖',k:'book open'},{e:'📓',k:'notebook'},{e:'📔',k:'notebook decorated'},
      {e:'📒',k:'ledger'},{e:'📕',k:'red book'},{e:'📗',k:'green book'},{e:'📘',k:'blue book'},
      {e:'📙',k:'orange book'},{e:'📝',k:'memo note'},{e:'✏️',k:'pencil'},{e:'✒️',k:'fountain pen'},
      {e:'🖊️',k:'pen'},{e:'🖋️',k:'fountain pen'},{e:'🖌️',k:'paintbrush'},{e:'🖍️',k:'crayon'},
      {e:'📎',k:'paperclip'},{e:'📌',k:'pushpin'},{e:'📍',k:'round pushpin'},{e:'🔗',k:'link'},
      {e:'📂',k:'folder open'},{e:'📁',k:'folder'},{e:'🗂️',k:'dividers'},{e:'📅',k:'calendar date'},
      {e:'📆',k:'calendar'},{e:'🗓️',k:'calendar spiral'},{e:'📇',k:'card index'},{e:'📈',k:'chart up'},
      {e:'📉',k:'chart down'},{e:'📊',k:'bar chart'},{e:'📋',k:'clipboard'},{e:'📌',k:'pin'},
      {e:'🎯',k:'target bullseye goal'},{e:'🚀',k:'rocket launch'},{e:'🛒',k:'cart shopping'},{e:'💼',k:'briefcase work'},
      {e:'🗝️',k:'key'},{e:'🔑',k:'key'},{e:'🔒',k:'lock'},{e:'🔓',k:'unlock'},
      {e:'💰',k:'money bag'},{e:'💵',k:'dollar money'},{e:'💴',k:'yen money'},{e:'💶',k:'euro money'},
      {e:'💷',k:'pound money'},{e:'💳',k:'credit card'},{e:'🎁',k:'gift present'},{e:'🎀',k:'ribbon'}
    ]},
    { id: 'symbols', label: '⭐ Symbols', emojis: [
      {e:'❤️',k:'heart red love'},{e:'🧡',k:'heart orange'},{e:'💛',k:'heart yellow'},{e:'💚',k:'heart green'},
      {e:'💙',k:'heart blue'},{e:'💜',k:'heart purple'},{e:'🖤',k:'heart black'},{e:'🤍',k:'heart white'},
      {e:'🤎',k:'heart brown'},{e:'💔',k:'broken heart'},{e:'💕',k:'two hearts'},{e:'💖',k:'sparkling heart'},
      {e:'💗',k:'growing heart'},{e:'💘',k:'heart arrow'},{e:'💝',k:'heart ribbon'},{e:'💟',k:'heart decoration'},
      {e:'⭐',k:'star'},{e:'🌟',k:'glowing star'},{e:'✨',k:'sparkles magic'},{e:'💫',k:'dizzy'},
      {e:'⚡',k:'lightning power fast'},{e:'🔥',k:'fire hot trending'},{e:'☀️',k:'sun'},{e:'🌈',k:'rainbow'},
      {e:'☁️',k:'cloud'},{e:'❄️',k:'snowflake'},{e:'💧',k:'droplet water'},{e:'🌊',k:'wave ocean'},
      {e:'✅',k:'check done'},{e:'☑️',k:'check box'},{e:'✔️',k:'check mark'},{e:'❌',k:'cross no'},
      {e:'❎',k:'cross mark'},{e:'➕',k:'plus add'},{e:'➖',k:'minus'},{e:'➗',k:'divide'},
      {e:'✖️',k:'multiply'},{e:'🟰',k:'equal'},{e:'♾️',k:'infinity'},{e:'❗',k:'exclamation'},
      {e:'❓',k:'question'},{e:'❕',k:'white exclamation'},{e:'❔',k:'white question'},{e:'‼️',k:'double exclamation'},
      {e:'⚠️',k:'warning caution'},{e:'🚫',k:'prohibited no'},{e:'⛔',k:'no entry'},{e:'🔞',k:'no under 18'},
      {e:'🔴',k:'red circle'},{e:'🟠',k:'orange circle'},{e:'🟡',k:'yellow circle'},{e:'🟢',k:'green circle'},
      {e:'🔵',k:'blue circle'},{e:'🟣',k:'purple circle'},{e:'⚫',k:'black circle'},{e:'⚪',k:'white circle'},
      {e:'🟥',k:'red square'},{e:'🟧',k:'orange square'},{e:'🟨',k:'yellow square'},{e:'🟩',k:'green square'},
      {e:'🟦',k:'blue square'},{e:'🟪',k:'purple square'},{e:'⬛',k:'black square'},{e:'⬜',k:'white square'}
    ]},
    { id: 'food', label: '🍔 Food', emojis: [
      {e:'🍎',k:'apple red'},{e:'🍏',k:'apple green'},{e:'🍊',k:'orange'},{e:'🍋',k:'lemon'},
      {e:'🍌',k:'banana'},{e:'🍉',k:'watermelon'},{e:'🍇',k:'grapes'},{e:'🍓',k:'strawberry'},
      {e:'🫐',k:'blueberries'},{e:'🍈',k:'melon'},{e:'🍒',k:'cherries'},{e:'🍑',k:'peach'},
      {e:'🥭',k:'mango'},{e:'🍍',k:'pineapple'},{e:'🥥',k:'coconut'},{e:'🥝',k:'kiwi'},
      {e:'🥑',k:'avocado'},{e:'🍆',k:'eggplant'},{e:'🥔',k:'potato'},{e:'🥕',k:'carrot'},
      {e:'🌽',k:'corn'},{e:'🌶️',k:'chili pepper spicy'},{e:'🥒',k:'cucumber'},{e:'🥬',k:'leafy greens'},
      {e:'🥦',k:'broccoli'},{e:'🧄',k:'garlic'},{e:'🧅',k:'onion'},{e:'🍔',k:'burger'},
      {e:'🍟',k:'fries'},{e:'🍕',k:'pizza'},{e:'🌭',k:'hot dog'},{e:'🥪',k:'sandwich'},
      {e:'🌮',k:'taco'},{e:'🌯',k:'burrito'},{e:'🫔',k:'tamale'},{e:'🥙',k:'pita'},
      {e:'🥚',k:'egg'},{e:'🍳',k:'fried egg'},{e:'🥘',k:'shallow pan'},{e:'🍲',k:'stew'},
      {e:'🫕',k:'fondue'},{e:'🍜',k:'ramen noodles'},{e:'🍝',k:'spaghetti pasta'},{e:'🍛',k:'curry'},
      {e:'🍣',k:'sushi'},{e:'🍱',k:'bento'},{e:'🥟',k:'dumpling'},{e:'🦪',k:'oyster'},
      {e:'🍤',k:'fried shrimp'},{e:'🍚',k:'rice'},{e:'🍙',k:'rice ball'},{e:'🍘',k:'rice cracker'},
      {e:'🍥',k:'fish cake'},{e:'🥠',k:'fortune cookie'},{e:'🍢',k:'oden'},{e:'🍡',k:'dango'},
      {e:'☕',k:'coffee hot'},{e:'🍵',k:'tea'},{e:'🧉',k:'mate'},{e:'🍺',k:'beer'},
      {e:'🍻',k:'cheers beer'},{e:'🥂',k:'champagne clink'},{e:'🍷',k:'wine'},{e:'🥃',k:'whiskey'},
      {e:'🍸',k:'cocktail'},{e:'🍹',k:'tropical drink'},{e:'🥤',k:'drink cup'},{e:'🧋',k:'bubble tea boba'},
      {e:'🍰',k:'cake slice'},{e:'🎂',k:'birthday cake'},{e:'🧁',k:'cupcake'},{e:'🥧',k:'pie'},
      {e:'🍪',k:'cookie'},{e:'🍩',k:'donut'},{e:'🍫',k:'chocolate'},{e:'🍬',k:'candy'},
      {e:'🍭',k:'lollipop'},{e:'🍮',k:'custard pudding'},{e:'🍯',k:'honey'}
    ]},
    { id: 'activity', label: '⚽ Activity', emojis: [
      {e:'⚽',k:'soccer football'},{e:'🏀',k:'basketball'},{e:'🏈',k:'american football'},{e:'⚾',k:'baseball'},
      {e:'🥎',k:'softball'},{e:'🎾',k:'tennis'},{e:'🏐',k:'volleyball'},{e:'🏉',k:'rugby'},
      {e:'🎱',k:'pool ball'},{e:'🏓',k:'ping pong'},{e:'🏸',k:'badminton'},{e:'🥅',k:'goal net'},
      {e:'🏒',k:'ice hockey'},{e:'🏑',k:'field hockey'},{e:'🥍',k:'lacrosse'},{e:'🏏',k:'cricket'},
      {e:'⛳',k:'golf'},{e:'🏹',k:'archery'},{e:'🎣',k:'fishing'},{e:'🥊',k:'boxing'},
      {e:'🥋',k:'martial arts'},{e:'🎽',k:'running shirt'},{e:'🛹',k:'skateboard'},{e:'🛼',k:'roller skate'},
      {e:'🛷',k:'sled'},{e:'⛸️',k:'ice skate'},{e:'🥌',k:'curling'},{e:'🎿',k:'ski'},
      {e:'⛷️',k:'skier'},{e:'🏂',k:'snowboard'},{e:'🪂',k:'parachute'},{e:'🏋️',k:'weight lifting'},
      {e:'🤸',k:'cartwheel'},{e:'🤺',k:'fencing'},{e:'🏇',k:'horse racing'},{e:'🚴',k:'cycling'},
      {e:'🚵',k:'mountain bike'},{e:'🏊',k:'swimming'},{e:'🤽',k:'water polo'},{e:'🚣',k:'rowboat'},
      {e:'🧗',k:'climbing'},{e:'🏄',k:'surfing'},{e:'🏆',k:'trophy award winner'},{e:'🥇',k:'gold medal first'},
      {e:'🥈',k:'silver medal second'},{e:'🥉',k:'bronze medal third'},{e:'🏅',k:'medal'},{e:'🎖️',k:'military medal'},
      {e:'🎫',k:'ticket'},{e:'🎟️',k:'admission ticket'},{e:'🎪',k:'circus tent'},{e:'🎭',k:'masks theater'},
      {e:'🎨',k:'palette art'},{e:'🎬',k:'clapper movie'},{e:'🎤',k:'microphone sing karaoke'},{e:'🎧',k:'headphones music'},
      {e:'🎼',k:'music score'},{e:'🎵',k:'music note'},{e:'🎶',k:'music notes'},{e:'🎹',k:'piano keyboard'},
      {e:'🎷',k:'saxophone'},{e:'🎺',k:'trumpet'},{e:'🎸',k:'guitar'},{e:'🎻',k:'violin'},
      {e:'🪕',k:'banjo'},{e:'🥁',k:'drum'},{e:'🪘',k:'long drum'}
    ]},
    { id: 'places', label: '🏠 Places', emojis: [
      {e:'🏠',k:'house home'},{e:'🏡',k:'house garden'},{e:'🏘️',k:'houses neighborhood'},{e:'🏚️',k:'derelict house'},
      {e:'🏗️',k:'construction'},{e:'🏢',k:'office building'},{e:'🏬',k:'department store'},{e:'🏣',k:'japanese post'},
      {e:'🏤',k:'post office'},{e:'🏥',k:'hospital'},{e:'🏦',k:'bank'},{e:'🏨',k:'hotel'},
      {e:'🏪',k:'convenience store'},{e:'🏫',k:'school'},{e:'🏛️',k:'classical building museum'},{e:'💒',k:'wedding'},
      {e:'🕌',k:'mosque'},{e:'🕍',k:'synagogue'},{e:'⛪',k:'church'},{e:'🛕',k:'hindu temple'},
      {e:'🕋',k:'kaaba'},{e:'⛩️',k:'shinto shrine'},{e:'🏯',k:'japanese castle'},{e:'🏰',k:'castle europe'},
      {e:'🗼',k:'tokyo tower'},{e:'🗽',k:'statue of liberty'},{e:'🎠',k:'carousel'},{e:'🎡',k:'ferris wheel'},
      {e:'🎢',k:'roller coaster'},{e:'💈',k:'barber'},{e:'🎪',k:'circus'},{e:'🚂',k:'steam locomotive'},
      {e:'🚆',k:'train'},{e:'🚇',k:'metro'},{e:'🚊',k:'tram'},{e:'🚝',k:'monorail'},
      {e:'🚄',k:'bullet train'},{e:'🚅',k:'shinkansen'},{e:'🚈',k:'light rail'},{e:'🚂',k:'locomotive'},
      {e:'🚗',k:'car automobile'},{e:'🚕',k:'taxi'},{e:'🚙',k:'suv'},{e:'🚌',k:'bus'},
      {e:'🚎',k:'trolley bus'},{e:'🏎️',k:'race car'},{e:'🚓',k:'police car'},{e:'🚑',k:'ambulance'},
      {e:'🚒',k:'fire engine'},{e:'🚐',k:'minibus'},{e:'🛻',k:'pickup truck'},{e:'🚚',k:'delivery truck'},
      {e:'🚛',k:'articulated truck'},{e:'🚜',k:'tractor'},{e:'🛵',k:'motor scooter'},{e:'🏍️',k:'motorcycle'},
      {e:'🛺',k:'auto rickshaw'},{e:'🚲',k:'bicycle bike'},{e:'🛴',k:'kick scooter'},{e:'🛹',k:'skateboard'},
      {e:'🚁',k:'helicopter'},{e:'✈️',k:'airplane'},{e:'🛫',k:'takeoff'},{e:'🛬',k:'landing'},
      {e:'⛵',k:'sailboat'},{e:'🚤',k:'speedboat'},{e:'🛥️',k:'motorboat'},{e:'🛳️',k:'passenger ship'},
      {e:'⛴️',k:'ferry'},{e:'🚢',k:'ship'},{e:'⚓',k:'anchor'}
    ]},
    { id: 'nature', label: '🌿 Nature', emojis: [
      {e:'🐶',k:'dog puppy'},{e:'🐱',k:'cat kitten'},{e:'🐭',k:'mouse'},{e:'🐹',k:'hamster'},
      {e:'🐰',k:'rabbit bunny'},{e:'🦊',k:'fox'},{e:'🐻',k:'bear'},{e:'🐼',k:'panda'},
      {e:'🐨',k:'koala'},{e:'🐯',k:'tiger'},{e:'🦁',k:'lion'},{e:'🐮',k:'cow'},
      {e:'🐷',k:'pig'},{e:'🐸',k:'frog'},{e:'🐵',k:'monkey'},{e:'🙈',k:'see no evil'},
      {e:'🙉',k:'hear no evil'},{e:'🙊',k:'speak no evil'},{e:'🐔',k:'chicken'},{e:'🐧',k:'penguin'},
      {e:'🐦',k:'bird'},{e:'🐤',k:'baby chick'},{e:'🦆',k:'duck'},{e:'🦅',k:'eagle'},
      {e:'🦉',k:'owl'},{e:'🦇',k:'bat'},{e:'🐺',k:'wolf'},{e:'🐗',k:'boar'},
      {e:'🐴',k:'horse face'},{e:'🦄',k:'unicorn'},{e:'🐝',k:'bee'},{e:'🐛',k:'bug'},
      {e:'🦋',k:'butterfly'},{e:'🐌',k:'snail'},{e:'🐞',k:'ladybug'},{e:'🐜',k:'ant'},
      {e:'🦗',k:'cricket'},{e:'🕷️',k:'spider'},{e:'🦂',k:'scorpion'},{e:'🐢',k:'turtle'},
      {e:'🐍',k:'snake'},{e:'🦎',k:'lizard'},{e:'🦖',k:'t-rex dinosaur'},{e:'🦕',k:'sauropod'},
      {e:'🐙',k:'octopus'},{e:'🦑',k:'squid'},{e:'🦐',k:'shrimp'},{e:'🦞',k:'lobster'},
      {e:'🦀',k:'crab'},{e:'🐡',k:'blowfish'},{e:'🐠',k:'tropical fish'},{e:'🐟',k:'fish'},
      {e:'🐬',k:'dolphin'},{e:'🐳',k:'whale'},{e:'🦈',k:'shark'},{e:'🐊',k:'crocodile'},
      {e:'🐅',k:'tiger'},{e:'🐆',k:'leopard'},{e:'🦓',k:'zebra'},{e:'🦍',k:'gorilla'},
      {e:'🐘',k:'elephant'},{e:'🦒',k:'giraffe'},{e:'🐫',k:'camel'},{e:'🦙',k:'llama'},
      {e:'🐐',k:'goat'},{e:'🐏',k:'ram'},{e:'🐑',k:'sheep'},{e:'🐎',k:'horse'},
      {e:'🌵',k:'cactus'},{e:'🎄',k:'christmas tree'},{e:'🌲',k:'evergreen tree'},{e:'🌳',k:'tree'},
      {e:'🌴',k:'palm tree'},{e:'🌱',k:'seedling'},{e:'🌿',k:'herb'},{e:'☘️',k:'shamrock'},
      {e:'🍀',k:'four leaf clover luck'},{e:'🎋',k:'tanabata tree'},{e:'🎍',k:'bamboo'},{e:'🌾',k:'ear of rice'},
      {e:'🌷',k:'tulip'},{e:'🌹',k:'rose'},{e:'🥀',k:'wilted flower'},{e:'🌺',k:'hibiscus'},
      {e:'🌸',k:'cherry blossom'},{e:'🌼',k:'blossom'},{e:'🌻',k:'sunflower'},{e:'💐',k:'bouquet'}
    ]}
  ]
};
